[tool.poetry]
name = "my-backlight"
version = "0.1.0"
description = ""
authors = ["fornav <vfornasiero@gmail.com>"]
packages = [{include = "my_backlight"}]
include = [
    { path = "configs/config.yaml", format = ["sdist", "wheel"] },
]

[tool.poetry.scripts]
vrgb = "my_backlight.cli:main"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.0"
pyyaml = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "ruff (==0.16.6)",
    "pytest (==9.1.1)"
]

[tool.ruff]
line-length = 88

[tool.ruff.lint.pydocstyle]
convention = "google"
